CREATE DATABASE IF NOT EXISTS punto_venta
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE punto_venta;

CREATE TABLE IF NOT EXISTS categoria (
    ID_CATEGORIA INT NOT NULL AUTO_INCREMENT,
    ESTADO BOOLEAN DEFAULT TRUE,
    NOMBRE VARCHAR(65),
    DESCRIPCION VARCHAR(65),
    PRIMARY KEY (ID_CATEGORIA)
);

CREATE TABLE IF NOT EXISTS cliente (
    ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
    ESTADO BOOLEAN DEFAULT TRUE,
    NOMBRE VARCHAR(85),
    APELLIDO VARCHAR(85),
    EMAIL VARCHAR(85),
    TELEFONO VARCHAR(25),
    FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE IF NOT EXISTS producto (
    ID_PRODUCTO INT NOT NULL AUTO_INCREMENT,
    ESTADO BOOLEAN DEFAULT TRUE,
    NOMBRE VARCHAR(65),
    DESCRIPCION VARCHAR(65),
    PRECIO DECIMAL(10,2),
    STOCK INT,
    ID_CATEGORIA INT,
    PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT FK_PRODUCTO_CATEGORIA
        FOREIGN KEY (ID_CATEGORIA)
        REFERENCES categoria(ID_CATEGORIA)
);

CREATE TABLE IF NOT EXISTS pedido (
    ID_PEDIDO INT NOT NULL AUTO_INCREMENT,
    ESTADO BOOLEAN DEFAULT TRUE,
    FECHA_PEDIDO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ESTADO_PEDIDO BOOLEAN DEFAULT TRUE,
    TOTAL DECIMAL(10,2),
    ID_CLIENTE INT,
    PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_PEDIDO_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES cliente(ID_CLIENTE)
);

CREATE TABLE IF NOT EXISTS pedido_detalle (
    ID_PEDIDO_DETALLE INT NOT NULL AUTO_INCREMENT,
    CANTIDAD INT,
    PRECIO_UNITARIO DECIMAL(10,2),
    SUBTOTAL DECIMAL(10,2),
    ID_PEDIDO INT,
    ID_PRODUCTO INT,
    PRIMARY KEY (ID_PEDIDO_DETALLE),
    CONSTRAINT FK_DETALLE_PEDIDO
        FOREIGN KEY (ID_PEDIDO)
        REFERENCES pedido(ID_PEDIDO),
    CONSTRAINT FK_DETALLE_PRODUCTO
        FOREIGN KEY (ID_PRODUCTO)
        REFERENCES producto(ID_PRODUCTO)
);

-- Datos de ejemplo. Los WHERE NOT EXISTS evitan duplicarlos al repetir el script.
INSERT INTO categoria (ESTADO, NOMBRE, DESCRIPCION)
SELECT TRUE, 'Tecnologia', 'Productos tecnologicos'
WHERE NOT EXISTS (
    SELECT 1 FROM categoria WHERE NOMBRE = 'Tecnologia'
);

INSERT INTO cliente
    (ESTADO, NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHA_REGISTRO)
SELECT
    TRUE, 'Carlos', 'Perez',
    'carlos.perez@correo.com', '55551234', CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM cliente WHERE EMAIL = 'carlos.perez@correo.com'
);

INSERT INTO producto
    (ESTADO, NOMBRE, DESCRIPCION, PRECIO, STOCK, ID_CATEGORIA)
SELECT
    TRUE, 'Teclado mecanico', 'Teclado para computadora',
    350.00, 10, c.ID_CATEGORIA
FROM categoria c
WHERE c.NOMBRE = 'Tecnologia'
  AND NOT EXISTS (
      SELECT 1 FROM producto WHERE NOMBRE = 'Teclado mecanico'
  )
LIMIT 1;

INSERT INTO pedido
    (ESTADO, FECHA_PEDIDO, ESTADO_PEDIDO, TOTAL, ID_CLIENTE)
SELECT
    TRUE, CURRENT_TIMESTAMP, TRUE, 350.00, c.ID_CLIENTE
FROM cliente c
WHERE c.EMAIL = 'carlos.perez@correo.com'
  AND NOT EXISTS (
      SELECT 1 FROM pedido p
      WHERE p.ID_CLIENTE = c.ID_CLIENTE AND p.TOTAL = 350.00
  )
LIMIT 1;

INSERT INTO pedido_detalle
    (CANTIDAD, PRECIO_UNITARIO, SUBTOTAL, ID_PEDIDO, ID_PRODUCTO)
SELECT
    1, 350.00, 350.00, p.ID_PEDIDO, pr.ID_PRODUCTO
FROM pedido p
JOIN cliente c ON c.ID_CLIENTE = p.ID_CLIENTE
JOIN producto pr ON pr.NOMBRE = 'Teclado mecanico'
WHERE c.EMAIL = 'carlos.perez@correo.com'
  AND p.TOTAL = 350.00
  AND NOT EXISTS (
      SELECT 1 FROM pedido_detalle d
      WHERE d.ID_PEDIDO = p.ID_PEDIDO
        AND d.ID_PRODUCTO = pr.ID_PRODUCTO
  )
LIMIT 1;

SHOW TABLES;
